### ISSUE TITLE
Payment system 

### ISSUE THREAD

**Issue by Kerrialn** [Residewise/residewise.com#2]
integrate a payment system. 

- decide on payment gateway 
- use interfaces and make easy to add other providers

**Comment by Tj0rk** [comment]
The most common payment would be stripe but this would be too expensive (but very convenient for users) 
I think the best option is probably to get the money with direct debit. 
We need to think of a way to transfer the money automatically from our bank account to the landlords. 
I think we have to come up with something like Wise. With our direct debit we automatically can give the transaction a reference number and with this number, we know for whom the payment is. We need a dashboard to see if every transaction was made. So we can solve the problem ourselves and not get an angry landlord.
